export enum AuthError {
   INVALID_CREDENTIALS = 'ERROR.INVALID_CREDENTIALS',

   EMAIL_USERNAME_ALREADY_IN_USE = 'ERROR.EMAIL_USERNAME_ALREADY_IN_USE',

   PASSWORD_TOO_WEAK = 'ERROR.PASSWORD_TOO_WEAK',
}
